### ISSUE TITLE
No bash output, error in log file

### ISSUE THREAD

**Issue by satmandu** [fredley/raspi-turntouch#2]
I'm not seeing any output from the bash command, but monitor is seeing the button presses.

Any ideas?

(I'm running this on a chip device running debian not a raspberry pi, but they're pretty similar devices otherwise.)

output in /var/log/turntouch.log:
```
00:05:45,591 monitor INFO Performing North Press
00:05:45,617 apscheduler.scheduler INFO Removed job 75cf2bc0e2794aad8a2b0f83b5e13e11
00:05:45,638 apscheduler.executors.default ERROR Job "TurnTouch.deduplicate_buttons (trigger: date[2018-03-06 00:05:45 EST], next run at: 2018-03-06 00:05:45 EST)" raised an exception
Traceback (most recent call last):
  File "/home/satmandu/turntouch/controllers/bash_controller.py", line 13, in perform
    ).decode('utf-8').strip())
TypeError: log() missing 1 required positional argument: 'msg'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/apscheduler/executors/base.py", line 125, in run_job
    retval = job.func(*job.args, **job.kwargs)
  File "monitor.py", line 117, in deduplicate_buttons
    self.perform(direction, 'Press')
  File "monitor.py", line 125, in perform
    self.controllers[action['type']].perform(action)
  File "/home/satmandu/turntouch/controllers/bash_controller.py", line 15, in perform
    logger.log("Something went wrong: {}".format(e))
TypeError: log() missing 1 required positional argument: 'msg'
```

**Comment by fredley** [comment]
This is actually just a bug in the log line, I've got some work outstanding that fixes this, that refactors how logging works a little. I'll get it pushed up tonight hopefully!

If you want to fix this in the meantime, replace `logger.log` with `logger.info`

**Comment by satmandu** [comment]
Exactly what I needed. Thanks!
